<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>84989818-e33f-473a-8a54-12ef25ce5552</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="pdt-container"]:nth-child(3) &gt; [class="addCart-Btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Add to cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>2892dd6c-f676-4b2a-bb2d-3755cbda851b</webElementGuid>
    </webElementProperties>
</WebElementEntity>