<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5486ef0b-cb1b-453a-a7c1-4ddd5ba25c63</elementGuidId>
    <imagePath></imagePath>
    <name>button_shop_now</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/a[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="shopBtn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Shop Now')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Shop Now</value>
        <webElementGuid>2892dd6c-f676-4b2a-bb2d-3755cbda851b</webElementGuid>
    </webElementProperties>
</WebElementEntity>